# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

os: osx
osx_image: xcode10.1
language: swift
xcode_project: LegibleError.xcodeproj
xcode_scheme: LegibleError-Package

jobs:
  include:
    - stage: pretest
      name: Check Linux tests are sync’d
      install: swift test --generate-linuxmain
      script: git diff --exit-code

    - name: macOS / Swift 4.0.3
      stage: test
      script: swift test --parallel -Xswiftc -swift-version -Xswiftc 4

    - name: macOS / Swift 4.2.1
      script: swift test --parallel

    - name: macOS / Swift 5.0.0
      osx_image: xcode10.2
      script: swift test --parallel

    - &xcodebuild
      before_install: swift package generate-xcodeproj --enable-code-coverage
      xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone SE'
      name: iOS / Swift 4.2.1
      after_success: bash <(curl -s https://codecov.io/bash)

    - <<: *xcodebuild
      xcode_destination: 'platform=tvOS Simulator,OS=latest,name=Apple TV'
      name: tvOS / Swift 4.2.1

    - <<: *xcodebuild
      osx_image: xcode10.2
      xcode_destination: 'platform=macOS'
      name: macOS / Swift 5.0.0

    - &linux
      name: Linux / Swift 4.2.1
      env: SWIFT_VERSION=4.2.1
      os: linux
      language: generic
      sudo: false
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test

    - <<: *linux
      env: SWIFT_VERSION='5.0'
      name: Linux / Swift 5.0.0
      script: swift test --enable-code-coverage

    - stage: deploy
      if: branch =~ ^\d+\.\d+\.\d+$
      name: CocoaPods
      before_install: |
        curl -O https://raw.githubusercontent.com/mxcl/Path.swift/master/.github/deploy
        chmod u+x deploy
      install: brew install mxcl/made/swift-sh
      before_script: ./deploy generate-podspec
      script: pod trunk push
      after_success: ./deploy publish-release
