#if !canImport(ObjectiveC)
import XCTest

extension Test {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Test = [
        ("test_CocoaError", test_CocoaError),
        ("test_derived_annotated_NSError", test_derived_annotated_NSError),
        ("test_derived_NSError", test_derived_NSError),
        ("test_derived_underlying_NSError", test_derived_underlying_NSError),
        ("test_simple_Swift_enum", test_simple_Swift_enum),
        ("test_simple_Swift_enum_internal_scope", test_simple_Swift_enum_internal_scope),
        ("test_simple_Swift_enum_private_scope", test_simple_Swift_enum_private_scope),
        ("test_simple_Swift_enum_public_scope", test_simple_Swift_enum_public_scope),
        ("test_Swift_class", test_Swift_class),
        ("test_Swift_LocalizedError_class_with_errorDescription", test_Swift_LocalizedError_class_with_errorDescription),
        ("test_Swift_LocalizedError_class_without_errorDescription", test_Swift_LocalizedError_class_without_errorDescription),
        ("test_Swift_LocalizedError_enum_with_errorDescription", test_Swift_LocalizedError_enum_with_errorDescription),
        ("test_Swift_LocalizedError_enum_without_errorDescription", test_Swift_LocalizedError_enum_without_errorDescription),
        ("test_Swift_LocalizedError_struct_with_errorDescription", test_Swift_LocalizedError_struct_with_errorDescription),
        ("test_Swift_LocalizedError_struct_without_errorDescription", test_Swift_LocalizedError_struct_without_errorDescription),
        ("test_Swift_struct", test_Swift_struct),
        ("test_vanilla_NSError", test_vanilla_NSError),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Test.__allTests__Test),
    ]
}
#endif
